#!/bin/bash

source ./lib/validate_flags_copy

##############################################
image=""
number=""

##############################################
#parse flags
#defined in validate_flags_copy
parse_args "$@"
validate_args

##############################################
folder="./VMs"
original="$image"
image=$(basename "$image")

##############################################
#find last index in folder
image=${image%.*}
last=$(ls "$folder"/$image* 2>/dev/null | sort -V | tail -n 1)
num=${last%.*}
num=${num//[^0-9]/}
if [[ -z "$num" ]]; then
  num=0
fi
next=$((num + 1))

##############################################
for ((i=0; i<number; i++))
do
    cp "$original" "$folder/$image$((next + i)).qcow2"
done
echo ""
echo "###########     Image cloned successfully! :3      ###########"
echo ""
