#!/bin/bash

#TODO
#repeat for all scripts
#write tests

#update documentation

##############################################
source ./lib/replace_names.sh
source ./lib/parse_hostnames.sh

##############################################
FINAL_NODES=""

##############################################
parse_hostname_args "$@"
exclude_hostnames "$@"

##############################################
COMMAND="${!#}"

##############################################
for node in $FINAL_NODES; do
  replace_names "$node" "$COMMAND"
  ssh "$node" "$STRING" 2>&1 | while IFS= read -r line; do
        echo "$HOSTNAME: $line"
    done &
done 

##############################################
wait

