#!/bin/bash

source ./lib/validate_flags_start
source ./lib/bridge_network_setup

##############################################
netSetup=false

##############################################
parse_args "$@"  #validate_flags_start
validate_args


##############################################
if $netSetup; then
  network_setup  #bridge_network_setup
fi


i=1
for entry in ./VMs/*.qcow2; do
  idx=$i
  ((i++))
  
  qemu-system-x86_64 \
  -enable-kvm \
  -m 512 \
  -cpu host \
  -smp 2 \
  -drive file=$entry,format=qcow2 \
  -nographic \
  -netdev tap,id=net$idx,ifname=tap$idx,script=no,downscript=no \
  -device e1000,netdev=net$idx,mac=52:54:00:00:00:0$idx \
  &
done
