#!/bin/bash



expected_results=""

./mypdcp -w root@foo[1-2] ./testfile ~

pdsh -R ssh root@foo[1-2] ls | grep "testfile" > $output

if [[ "$expected_results" == "$output" ]];
then echo "Test 1: OK"
else echo "Test 1: Failed"
fi



expected_results=""

./mypdcp -w root@foo[1-3] -x root@foo2 ./testfile ~

pdsh -R ssh root@foo[1-3] -x root@foo2  ls | grep "testfile" > $output

if [[ "$expected_results" == "$output" ]];
then echo "Test 2: OK"
else echo "Test 2: Failed"
fi


expected_results=""

./mypdcp -w root@foo[1-2,3],foo4 ./testfile ~

pdsh -R ssh root@foo[1-2,3],foo4 ls | grep "testfile" > $output

if [[ "$expected_results" == "$output" ]];
then echo "Test 3: OK"
else echo "Test 3: Failed"
fi

