#!/bin/bash



##############################################
expected_lines=(
    "foo1: x"
    "foo2: x"
    "foo3: x"
    "foo4: x"
    "foo5: x"
)

output=$(./mypdsh -w "root@foo[1-5]" "echo x" 2>&1)

all_ok=true
for line in "${expected_lines[@]}"; do
    echo "$output" | grep -Fq "$line" || all_ok=false
done

if $all_ok; then
    echo "Test 1: OK"
else
    echo "Test 1: Failed"
fi



##############################################
expected_lines=(
    "foo1: x"
    "foo2: x"
    "foo4: x"
)

output=$(./mypdsh -w "root@foo[1-5]" -x "root@foo[3,5]" "echo x" 2>&1)

all_ok=true
for line in "${expected_lines[@]}"; do
    echo "$output" | grep -Fq "$line" || all_ok=false
done

if $all_ok; then
    echo "Test 2: OK"
else
    echo "Test 2: Failed"
fi




##############################################
expected_lines=(
    "foo1: root foo1"
    "foo2: root foo2"
    "foo3: root foo3"
    "foo4: root foo4"
    "foo5: root foo5"
)

output=$(./mypdsh -w "root@foo[1-5]" "echo %u %h" 2>&1)

all_ok=true
for line in "${expected_lines[@]}"; do
    echo "$output" | grep -Fq "$line" || all_ok=false
done

if $all_ok; then
    echo "Test 3: OK"
else
    echo "Test 3: Failed"
fi



##############################################
expected_lines=(
    "foo1: hello"
    "foo2: hello"
    "foo3: hello"
    "foo4: hello"
    "foo5: hello"
)

./mypdsh -w "root@foo[1-5]" "mkdir hello"
output=$(pdsh -R ssh -w "root@foo[1-5]" ls 2>&1 | grep "hello")

all_ok=true
for line in "${expected_lines[@]}"; do
    echo "$output" | grep -Fq "$line" || all_ok=false
done

if $all_ok; then
    echo "Test 4: OK"
else
    echo "Test 4: Failed"
fi

pdsh -R ssh -w "root@foo[1-5]" "rm -rf hello"





